<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HipsterCentralComp" ignored="1" name="Personal Loan" tests="5" failures="1" timestamp="05 Aug 2019 03:01:31 GMT" time="0.233" errors="0">
  <testcase name="Demo" time="0.03" classname="test.Day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.Demo(Day1.java:21)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="Plain" time="0.021" classname="test.Day2"/>
  <testcase name="LoginAPIHomeLoan" time="0.011" classname="test.Day4"/>
  <testcase name="MobileLoginHome" time="0.005" classname="test.Day4"/>
  <testcase name="WebloginHomeLoan" time="0.017" classname="test.Day4"/>
  <testcase name="SecondTest" time="0.0" classname="test.Day1">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
